### ISSUE TITLE
About showing the Web interface in the video

### ISSUE THREAD

**Issue by 834799106** [kamwoh/orthohash#3]
Thank you very much for your work. I am very interested in showing the Web interface in the video. Is there any code for this part?

**Comment by jiuntian** [comment]
Hi,
Thanks for your interest in our work. We will open source this part of code soon. Please expect us to notify you here again upon the release.

**Comment by jiuntian** [comment]
Hi @834799106 , thanks for your patience, we have open-sourced the web interface in our open-source image retrieval framework https://github.com/CISiPLab/cisip-FIRe. 
See more at: https://fast-image-retrieval.readthedocs.io/en/latest/tutorials.html#inference-trained-model.

I will close this issue now.
